export const PRESET_EXAMPLES = [
  {
    id: "inc-nonzero",
    operation: "INC",
    title: "INC on a nonzero register",
    description: "Shows how increment propagates through the binary representation of register 0.",
    learningGoal: "Observe carry handling while increasing a positive register value by one.",
    payload: {
      operation: "INC",
      register_values: [3, 0, 0, 0, 0],
      parameters: { target: 0 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "dec-nonzero",
    operation: "DEC",
    title: "DEC on a nonzero register",
    description: "Decrements register 0 from a positive value and halts successfully.",
    learningGoal: "Observe borrowing while decreasing a positive binary value.",
    payload: {
      operation: "DEC",
      register_values: [5, 0, 0, 0, 0],
      parameters: { target: 0 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "dec-zero",
    operation: "DEC",
    title: "DEC on zero",
    description: "Demonstrates the immediate reject behavior when attempting to decrement zero.",
    learningGoal: "Show the operation-level rejection condition for decrement.",
    payload: {
      operation: "DEC",
      register_values: [0, 0, 0, 0, 0],
      parameters: { target: 0 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "cz-zero",
    operation: "CZ",
    title: "CZ on zero",
    description: "Checks a blank binary tape and accepts because the register is zero.",
    learningGoal: "Show why a blank tape head corresponds to zero in this simulator.",
    payload: {
      operation: "CZ",
      register_values: [0, 0, 0, 0, 0],
      parameters: { target: 0 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "cz-nonzero",
    operation: "CZ",
    title: "CZ on nonzero",
    description: "Rejects because the selected register begins with a binary digit on tape.",
    learningGoal: "Contrast the zero case with a nonzero register input.",
    payload: {
      operation: "CZ",
      register_values: [2, 0, 0, 0, 0],
      parameters: { target: 0 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "cmp-equal",
    operation: "CMP",
    title: "CMP equal registers",
    description: "Compares two registers with equal binary contents and accepts.",
    learningGoal: "Show parallel tape comparison for equal register values.",
    payload: {
      operation: "CMP",
      register_values: [4, 4, 0, 0, 0],
      parameters: { left: 0, right: 1 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "cmp-unequal",
    operation: "CMP",
    title: "CMP unequal registers",
    description: "Compares two registers with different binary contents and rejects.",
    learningGoal: "Show how mismatched symbols lead to rejection during comparison.",
    payload: {
      operation: "CMP",
      register_values: [4, 3, 0, 0, 0],
      parameters: { left: 0, right: 1 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "clr-populated",
    operation: "CLR",
    title: "CLR on a populated register",
    description: "Clears register 0 by erasing all binary digits and returning to the tape start.",
    learningGoal: "Observe how the machine removes a register value until only blanks remain.",
    payload: {
      operation: "CLR",
      register_values: [6, 0, 0, 0, 0],
      parameters: { target: 0 },
      num_registers: 5,
      include_steps: true,
    },
  },
  {
    id: "cpy-source-destination",
    operation: "CPY",
    title: "CPY from source to destination",
    description: "Copies the value of register 1 into register 0.",
    learningGoal: "Show how source bits are transferred to a destination tape in parallel.",
    payload: {
      operation: "CPY",
      register_values: [0, 5, 0, 0, 0],
      parameters: { destination: 0, source: 1 },
      num_registers: 5,
      include_steps: true,
    },
  },
];

